name: ht_countries_firestore
description: A Firestore implementation for the `ht_countries_client` interface.
repository: https://github.com/headlines-toolkit/ht-countries-firestore
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  cloud_firestore: ^5.6.6
  flutter:
    sdk: flutter
  ht_countries_client:
    git:
      url: https://github.com/headlines-toolkit/ht-countries-client.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
